simba:
  jdbc:
    enabled: true
#  redis:
#    enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simba_db
    username: root
    password: root
  task:
    scheduling:
      pool:
        size: 2
  data:
    redis:
      url: redis://localhost:6379

logging:
  level:
    me.ahoo.simba: debug
